BEGIN;

CREATE TABLE IF NOT EXISTS users(
   id          SERIAL PRIMARY KEY,
   password    TEXT NOT NULL,
   email       TEXT UNIQUE NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS users_email_idx ON users USING btree (email);

COMMIT;