package moonlanding

import (
	"bytes"
	"fmt"

	"database.example/models/users"
)

//MakeMoonGreatAgain is our example that uses model we will mock in test
func MakeMoonGreatAgain() string {

	var buf bytes.Buffer
	//randomly generated by debian comitee number
	rand := 4

	moonPerson, err := users.Store.FindByEmail("landing@moon.com")

	if err != nil {
		buf.WriteString(fmt.Sprintf("Houstong we have a problem %s\n", err))
		buf.WriteString("Damage!\n")
		return buf.String()
	}

	buf.WriteString(fmt.Sprintf("%s %s\n", moonPerson.Email, "is landing on the moon"))
	buf.WriteString(fmt.Sprintf("After %d hours landing finished\n", rand))

	return buf.String()

}
